# Generated by Django 4.2.5 on 2023-09-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.RemoveField(
            model_name='image',
            name='upload_date',
        ),
    ]
