# Generated by Django 4.2.5 on 2023-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_remove_image_title_remove_image_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(null=True),
        ),
    ]
