# Generated by Django 4.2.5 on 2023-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0006_alter_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(default=1),
        ),
    ]
