# Generated by Django 4.2.5 on 2023-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0007_alter_image_image_file_alter_image_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
