# Generated by Django 4.2.5 on 2023-09-09 00:52

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0008_image_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('image_id', models.IntegerField(default=1)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('image', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
