# Generated by Django 4.2.5 on 2023-09-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0009_queryimage_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
